version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: ":paperclip:"
- package-ecosystem: npm
  directory: /packages/heart
  schedule:
    interval: daily
  commit-message:
    prefix: ":paperclip:"
- package-ecosystem: npm
  directory: /packages/page
  schedule:
    interval: daily
  commit-message:
    prefix: ":paperclip:"
