name = 'worker-place-backup'
workers_dev = false
account_id = 'ACCOUNT_ID'
routes = []
compatibility_date = '2022-05-28'
compatibility_flags = [ 'url_standard' ]
main = 'src/index.ts'

kv_namespaces = [
    { binding = 'SNAPSHOTS', id = '0c5060bc540f4eb1aa24ee55d2644e2a', preview_id = '0c5060bc540f4eb1aa24ee55d2644e2a' }
]

[triggers]
crons = [ '*/5 * * * *' ]

[[r2_buckets]]
binding = 'BACKUP'
bucket_name = 'worker-place-snapshots'
preview_bucket_name = 'worker-place-snapshots'
