name = 'worker-place-heart'
type = 'javascript'
workers_dev = false
account_id = 'd0238d3a1eebca7fc036cb766a5e538f'
routes = ['worker.place/api/*']
compatibility_date = '2022-05-19'

kv_namespaces = [
    { binding = 'TARGET_IMAGES', id = '1a9911b4d8c34a02a8809c512ae2e1d1' },
    { binding = 'SESSION_TOKENS', id = '28422365906245ccac227fee977031a3' },
    { binding = 'LOGS', id = 'ee33067035dd4ab5ad0352c1f8cd7413' },
    { binding = 'SNAPSHOTS', id = '0c5060bc540f4eb1aa24ee55d2644e2a' }
]

[build]
command = 'npm run build'

[build.upload]
dir = 'dist'
format = 'modules'
main = 'index.mjs'

[miniflare]
build_watch_dirs = ['src']
