name = 'worker-place-heart'
workers_dev = false
account_id = 'ACCOUNT_ID'
routes = [ 'worker.place/api/*' ]
compatibility_date = '2022-05-28'
compatibility_flags = [ 'durable_object_alarms', 'url_standard' ]
main = 'src/index.ts'

kv_namespaces = [
    { binding = 'TARGET_IMAGES', id = '1a9911b4d8c34a02a8809c512ae2e1d1', preview_id = '1a9911b4d8c34a02a8809c512ae2e1d1' },
    { binding = 'SESSION_TOKENS', id = '28422365906245ccac227fee977031a3', preview_id = '28422365906245ccac227fee977031a3' },
    { binding = 'LOGS', id = 'ee33067035dd4ab5ad0352c1f8cd7413', preview_id = 'ee33067035dd4ab5ad0352c1f8cd7413' },
    { binding = 'SNAPSHOTS', id = '0c5060bc540f4eb1aa24ee55d2644e2a', preview_id = '0c5060bc540f4eb1aa24ee55d2644e2a' }
]

[durable_objects]
bindings = [
  { name = 'PLACE', class_name = 'Place' }
]

[miniflare]
build_watch_dirs = [ 'place', 'src' ]

[[services]]
binding = 'ACCESSORY'
service = 'accessory'
environment = 'production'

[[r2_buckets]]
binding = 'SQUAD_IMAGES'
bucket_name = 'worker-place-squad-images'
preview_bucket_name = 'worker-place-squad-images'

[[migrations]]
tag = '2022-05-21'
new_classes = [ 'Place' ]

[triggers]
crons = [ '*/1 * * * *' ]

[[r2_buckets]]
binding = 'BACKUP'
bucket_name = 'worker-place-snapshots'
preview_bucket_name = 'worker-place-snapshots'
