name = 'worker-place-page'
account_id = 'ACCOUNT_ID'
workers_dev = false
compatibility_date = '2022-05-21'
compatibility_flags = [ 'url_standard' ]
main = '.output/server/index.mjs'
routes = [ 'worker.place', 'worker.place/about', 'worker.place/faq' ]

[build]
command = 'NITRO_PRESET=cloudflare npm run build'
