name = 'worker-place-page'
account_id = 'ACCOUNT_ID'
compatibility_date = '2022-05-21'
main = '.output/server/index.mjs'
routes = [ 'worker.place', 'worker.place/about', 'worker.place/faq', 'worker.place/_nuxt/*' ]

[build]
command = 'NITRO_PRESET=cloudflare npm run build'
